// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0GkCAAh8rILUQ4Y2qFlRYGVinRZF-azM',
    appId: '1:1003901213981:web:83c67c293615d47b0895f4',
    messagingSenderId: '1003901213981',
    projectId: 'flowrite-1b66f',
    authDomain: 'flowrite-1b66f.firebaseapp.com',
    storageBucket: 'flowrite-1b66f.firebasestorage.app',
    measurementId: 'G-CPNP6R4LJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd4yJjLAfJxJUiMaI1Ao3m1pAKxUZm2Bw',
    appId: '1:1003901213981:android:33eeb1c780d25ac20895f4',
    messagingSenderId: '1003901213981',
    projectId: 'flowrite-1b66f',
    storageBucket: 'flowrite-1b66f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV6zvr4-XzAYXULtDrLvu_f0unxK0ja1k',
    appId: '1:1003901213981:ios:cc33141253e8c3470895f4',
    messagingSenderId: '1003901213981',
    projectId: 'flowrite-1b66f',
    storageBucket: 'flowrite-1b66f.firebasestorage.app',
    androidClientId: '1003901213981-shuf5p11nvea99mktr8hbml8coi6r2af.apps.googleusercontent.com',
    iosClientId: '1003901213981-ek5o2sv7oqe444qad78tluiu89hvm2ab.apps.googleusercontent.com',
    iosBundleId: 'me.pi22by7.flowrite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV6zvr4-XzAYXULtDrLvu_f0unxK0ja1k',
    appId: '1:1003901213981:ios:cc33141253e8c3470895f4',
    messagingSenderId: '1003901213981',
    projectId: 'flowrite-1b66f',
    storageBucket: 'flowrite-1b66f.firebasestorage.app',
    androidClientId: '1003901213981-shuf5p11nvea99mktr8hbml8coi6r2af.apps.googleusercontent.com',
    iosClientId: '1003901213981-ek5o2sv7oqe444qad78tluiu89hvm2ab.apps.googleusercontent.com',
    iosBundleId: 'me.pi22by7.flowrite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0GkCAAh8rILUQ4Y2qFlRYGVinRZF-azM',
    appId: '1:1003901213981:web:9b4832f5b6bbffa70895f4',
    messagingSenderId: '1003901213981',
    projectId: 'flowrite-1b66f',
    authDomain: 'flowrite-1b66f.firebaseapp.com',
    storageBucket: 'flowrite-1b66f.firebasestorage.app',
    measurementId: 'G-E7LVYSDQ1Z',
  );

}