name: Generate Screenshots

on:
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [ main ]
    paths: 
      - 'lib/screens/**'
      - 'lib/widgets/**'
      - 'integration_test/**'
      - 'assets/screenshots/**'
  pull_request:
    branches: [ main ]
    paths: 
      - 'lib/screens/**'
      - 'lib/widgets/**'
      - 'integration_test/**'

jobs:
  screenshots:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Enable Linux desktop
      run: flutter config --enable-linux-desktop
    
    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
    
    - name: Build for Linux
      run: flutter build linux --release
    
    - name: Generate screenshots
      run: |
        export DISPLAY=:99
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
        sleep 3
        flutter test integration_test/app_test.dart -d linux
      continue-on-error: true
    
    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: screenshots
        path: |
          screenshots/
          assets/screenshots/
        retention-days: 30
    
    - name: Commit screenshots
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add assets/screenshots/
        git diff --staged --quiet || git commit -m "Update screenshots [skip ci]"
        git push
